[package]
name = "course"
version = "0.1.0"
authors = ["japrogramer <japrogramer@yahoo.com>"]
edition = "2018"

[dependencies]
cpython = "0.3"
serde =  { version = "1.0.101", features = ["derive"] }
futures = "0.3.1"

[[bin]]
name = "rl_course"
path = "src/main.rs"
